name = "DrillHoles"
uuid = "9d36f3b5-8124-4f7e-bcda-df733105c718"
authors = ["Rafael Caixeta <8386288+rmcaixeta@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
